#!/bin/bash

# Generates the mapnik style files, includes etc from
# their respective sources.

# Variable declarations on the form ${VAR} are substituted with
# the value of the corresponding enviroment variable VAR.

if [[ -z $TOPOSM_ENV_SET ]]; then
    echo "Error: TopOSM environment not set."
    exit 1
fi


SOURCEDIR="sources"
DESTDIR="processed"

# awk program to substitute environment variables
AWKFILTER='{while(match($0,"[$]{[^}]*}")){var=substr($0,RSTART+2,RLENGTH -3);gsub("[$]{"var"}",ENVIRON[var])}}1'

# grep filter to remove millstone junk
# see carto issue #212:
# https://github.com/mapbox/carto/issues/212
MILLSTONEFILTER="\[millstone\]"


mkdir -pv "$DESTDIR"

# Generate Mapnik XML from Carto templates
for SRC in `ls ${SOURCEDIR}/*.mml`; do
    echo "Processing $SRC..."
    DST="${DESTDIR}/`basename $SRC .mml`.xml"
        
    $CARTO $SRC | \
      grep -v "$MILLSTONEFILTER" | \
      awk "$AWKFILTER" \
      > $DST
        
    # read errors from output file
    # (carto writes these to stdout and always returns 0)
    cat $DST | grep "carto:"
done

# Process xml,inc,vrt,cfg files
for SRC in `ls ${SOURCEDIR}/*.{xml,inc,vrt,cfg}`; do
    echo "Processing $SRC..."
    DST="${DESTDIR}/`basename $SRC`"        
    cat $SRC | awk "$AWKFILTER" > $DST
done

echo "Done."

